log    =    log/cars_split_$(Cluster)_$(proc).log
error  =  error/cars_split_$(Cluster)_$(proc).err
output = output/cars_split_$(Cluster)_$(proc).out

universe = vanilla

executable = ./code/split.sh
arguments = $(file)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(file), col_index.txt

request_cpus = 8
request_memory = 4GB
request_disk = 4GB

queue file from ./code/split_file_list.txt
